### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by Luketep** [anchore/hub#6]
Hey guys,

you might have a typo in your `anchore_security_only` policies. At line 269 you specify `mongose`. Prior and after that you list different kind of databases. This lead me to believe, that you might mean `mongoose` or `mongodb` here.

https://github.com/anchore/hub/blob/master/sources/bundles/anchore_security_only.json

**Comment by nurmi** [comment]
Hi @Luketep - that rule is actually meant to detect and stop a known malicious package that was published at one point using the name 'mongose' as a way to try to create accidental installations of the intended 'mongoose' package by developers.  The purpose of that check is to provide examples of how an anchore policy can be used to prevent this type of security flaw!

There is an blog that describes this type of tactic here: https://iamakulov.com/notes/npm-malicious-packages/

Thank you for your report, let us know if this helps clarify

**Comment by Luketep** [comment]
Hey @nurmi , thanks for the explanation. Good to know, that you also think about those angles :) We can close this issue then. Take care!
